language: cpp

sudo: false

notification:
    email:
        on_success: change
        on_failure: always

matrix:
    include:
        - os: linux
          compiler: gcc
          env: INSTALL_CXX=g++-4.9 INSTALL_CC=gcc-4.9
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test' ]
                packages: [ 'g++-4.9', 'gcc-4.9' ]

        - os: linux
          compiler: clang
          env: INSTALL_CXX=clang++-3.7
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
                packages: [ 'clang-3.7' ]

before_install:
    - chmod +x build/buildtools-premake/bin/linux/premake5
    - chmod +x build/build.sh

before_script:
    - if [ -n "${INSTALL_CXX}" ]; then
        CXX=${INSTALL_CXX};
        $CXX --version;
      fi
    - if [ -n "${INSTALL_CC}" ]; then
        CC=${INSTALL_CC};
        $CC --version;
      fi
    - build/buildtools-premake/bin/premake.sh --version

script:
    - build/build.sh
