language: cpp

notification:
    email:
        on_success: change
        on_failure: always

os:
    - linux
    - osx

compiler:
    - clang

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
    packages:
        - clang-3.7
        - libsqlite3-dev

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install llvm38;
        brew install sqlite;
      fi

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        CXX=clang++-3.7;
        $CXX --version;
        CC=clang-3.7;
        $CC --version;
      fi

    - build/buildtools-premake/bin/build.sh
    - build/buildtools-premake/bin/premake.sh --version

script:
    - build/build.sh

after_success:
    - test/functional/blueprint/run-blueprint.sh
