language: cpp

notification:
    email:
        on_success: change
        on_failure: always

os:
    - linux
    - osx

compiler:
    - clang

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
    packages: [ 'clang-3.7' ]

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm37; fi

before_script:
    - if [[ -n "${INSTALL_CXX}" ]]; then CXX=${INSTALL_CXX}; fi
    - $CXX --version
    - build/buildtools-premake/bin/build.sh
    - build/buildtools-premake/bin/premake.sh --version

script:
    - build/build.sh
