language: cpp

notification:
    email:
        on_success: change
        on_failure: always

os:
    - linux
    - osx

compiler:
    - clang

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise' ]
    packages: [ 'clang-3.8' ]

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm37; fi

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CXX=clang++-3.8; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $CXX --version; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then clang --version; fi
    - build/buildtools-premake/bin/build.sh
    - build/buildtools-premake/bin/premake.sh --version

script:
    - build/build.sh

after_success:
    - test/functional/blueprint/run-blueprint.sh
