language: cpp

notification:
    email:
        on_success: change
        on_failure: always

matrix:
    include:
        - os: linux
          compiler: clang
          env: COMPILER=clang-3.7
          addons:
            apt:
                sources:  [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
                packages: [ 'clang-3.7', 'libsqlite3-dev' ]

        - os: linux
          compiler: clang
          env: COMPILER=clang-3.8
          addons:
            apt:
                sources:  [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise' ]
                packages: [ 'clang-3.8', 'libsqlite3-dev' ]

        - os: osx
          compiler: clang

    allow_failures:
        - env: COMPILER=clang-3.8

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install llvm38;
        brew install sqlite;
      fi

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export CXX=${COMPILER};
        $CXX --version;
      fi

    - build/buildtools-premake/bin/build.sh
    - build/buildtools-premake/bin/premake.sh --version

script:
    - build/build.sh

after_success:
    - test/functional/blueprint/run-blueprint.sh
