language: cpp

notification:
    email:
        on_success: change
        on_failure: always

matrix:
    include:
        - os: linux
          compiler: clang
          env: COMPILER=clang-3.7
          addons:
            apt:
                sources:  [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7' ]
                packages: [ 'clang-3.7', 'libclang-3.7-dev', 'libsqlite3-dev' ]

        - os: linux
          compiler: clang
          env: COMPILER=clang-3.8
          addons:
            apt:
                sources:  [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8' ]
                packages: [ 'clang-3.8', 'libclang-3.8-dev', 'libsqlite3-dev' ]

        - os: osx
          compiler: clang

    allow_failures:
        - env: COMPILER=clang-3.7
        - env: COMPILER=clang-3.8

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
      fi

    - dependencies/setup-premake.sh
    - dependencies/setup-sqlite.sh
    - dependencies/setup-llvm.sh

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        export CXX=${COMPILER};
        export CC=${COMPILER};
        $CXX --version;
      fi

script:
    - build/build.sh

after_success:
    - test/functional/blueprint/run-blueprint.sh
