environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS_VERSION: vs2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VS_VERSION: vs2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VS_VERSION: vs2013

install:
    - choco install wget
    - choco list -localonly

    - dependencies\setup.bat
    - build\generate.bat %VS_VERSION%

platform: x64

build:
  project: build\%VS_VERSION%\Blueprint.sln

on_finish:
    #- ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path output\bin\debug\BlueprintCore.Test.Results.xml))
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path output\bin\debug\BlueprintReflection.Test.Results.xml))

artifacts:
    - path: output\bin\debug\BlueprintReflection.Test.Results.xml
      name: BlueprintReflection.Test.Results.xml
